import com.google.inject.Guice;
import com.google.inject.Injector;
import com.spotify.apollo.Environment;
import com.spotify.apollo.httpservice.HttpService;
import com.spotify.apollo.httpservice.LoadingException;
import endpoints.TodoController;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    static Injector injector = Guice.createInjector();

    public static void main(String[] args) throws LoadingException {
        HttpService.boot(App::init, "microservice-001", args);
    }

    static void init(Environment environment) {
        environment.routingEngine()
            .registerAutoRoutes(injector.getInstance(TodoController.class));
    }
}
